### PR TITLE
Fixed minor typo in the pod.

### PR DESCRIPTION
**Pull request by manwar**
Hi @mohawk2 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks! But it's not a typo. If you look at the commit message, you will see why it is that way: `Pod::Markdown` doesn't handle `C<< blah >>`.

**Comment by manwar** [comment]
For some strange reason, it doesn't work. Take a look at pod here:

https://metacpan.org/pod/MooX::StrictHas

**Comment by mohawk2** [comment]
Yes, I noticed it after release, and fixed it on `master`. Not worth a release just for that.

**Comment by manwar** [comment]
Agreed :-)

**Comment by mohawk2** [comment]
...however, the dumb mistake of not calling the overridden `has` definitely was worth a release! :-D

**Pull request closed without merging**
